function animationinit() {
	$('#1').removeClass('hiddentext');
	setTimeout(function(){
		$('#filament').css({'animation-name':'animatefil_entry','opacity':'1'});
		$('#bulb-broken').css({'transition':'none'});
		$('#bulb-intact').css({'transition':'none'});
	},1000);
	setTimeout(function(){
		$('#bulb').css({'opacity':'1'});
	},2000);
	setTimeout(function(){
		$('#base').css({'transform':'translate(0,0)','opacity':'1'});
	},3000);
	setTimeout(function(){
		$('#1').addClass('hiddentext');
		$('#2').removeClass('hiddentext');
	},4000);
	setTimeout(function(){
		$('.st1').addClass('flicker');
		setTimeout(function(){
			$('#2').addClass('hiddentext');
			$('#3').removeClass('hiddentext');
			$('.st1').removeClass('flicker');;
			$('.st1').css({'fill':'#d8d8d8'});
		},3000);
		setTimeout(function(){
			$('#3').addClass('hiddentext');
			$('#filament-intact').css({'transform':'translate(0,100%)','opacity':'0'});
		},5000);
		setTimeout(function(){
			$('#4').removeClass('hiddentext');
			$('#filament-intact').css({'transform':'translate(0,0)','opacity':'1'});
		},6500);
		setTimeout(function(){
			$('#4').addClass('hiddentext');
			$('#5').removeClass('hiddentext');
		},8000);
		setTimeout(function(){
			$('.st1').css({'fill':'#FFC533'});
			$('#glow').css({'opacity':'1'});
			$('#filament-broken').css({'transform':'translate(0,0)'});
		},9000);
		setTimeout(function(){
			// $('#glow').css({'transform':'scale(1.2)'});
			$('#5').addClass('hiddentext');
			$('#6').removeClass('hiddentext');
		},11000);
		setTimeout(function(){
			$('#filament-intact').css({'opacity':'0'});
			$('#filament-broken').css({'opacity':'1'});
			$('#bulb-intact').css({'opacity':'0'});
			$('#glow').css({'opacity':'0'});
			$('#bulb-broken').css({'opacity':'1'});
			$('#bulb-broken').css({'transition':'transform 0.5s,opacity 0.5s'});
			$('#bulb-intact').css({'transition':'transform 0.5s,opacity 0.5s'});
			$('.st1').css({'fill':'#d8d8d8'});
		},12000);
		setTimeout(function(){
			$('#6').addClass('hiddentext');
			$('#filament-broken').css({'transform':'translate(0,100%)','opacity':'0'});
			$('#filament-intact').css({'transform':'translate(0,100%)'});
			$('#bulb-broken').css({'transform':'translate(0,100%)','opacity':'0'});
		},14000);
		setTimeout(function(){
			$('#7').removeClass('hiddentext');
		},16000);
		setTimeout(function(){
			$('#7').addClass('hiddentext');
			$('#8').removeClass('hiddentext');
		},17500);
		setTimeout(function(){
			$('#bulb-intact').css({'transform':'translate(0,0)','opacity':'1'});
			$('#filament-intact').css({'transform':'translate(0,0)','opacity':'1'});
		},18500);
		setTimeout(function(){
			// $('.st0').css({'fill':'#FFC533'});
			$('#8').addClass('hiddentext');
			$('#9').removeClass('hiddentext');
			$('.st1').css({'fill':'#FFC533'});
		},20500);
		setTimeout(function(){
			$('#10').removeClass('hiddentext');
			$('.bulblit').css({'transform':'translate(-50%,-50%) '});
			$('#glow').css({'opacity':'1'});
		},22500);
		setTimeout(function(){
			$('#9').addClass('hiddentext');
			$('#10').addClass('hiddentext');
			$('.bulblit').css({'opacity':'0'});
		},24500);
		setTimeout(function(){
			setTimeout(function(){
				$('.mnt2').removeClass('hidescn');
				$('.mnt2').css({'animation-name':'animate_scn'});
				$('.mnt2').css({'transform':'translate(0,0)'});
			},0);
			setTimeout(function(){
				$('.grd').removeClass('hidescn');
				$('.grd').css({'animation-name':'animate_scn'});
				$('.grd').css({'transform':'translate(0,0)'});
			},500);
			setTimeout(function(){
				$('.sky').removeClass('hidescn');
				$('.sky').css({'transform':'translate(0,0)'});
			},1000);
			setTimeout(function(){
				$('.mnt1').removeClass('hidescn');
				$('.mnt1').css({'animation-name':'animate_scn'});
				$('.mnt1').css({'transform':'translate(0,0)'});
			},1500);
			setTimeout(function(){
				$('.moon').removeClass('hidescn');
				$('.moon').css({'animation-name':'animate_moon'});
				$('.moon').css({'transform':'translate(0,0)'});
			},2000);
			setTimeout(function(){
				$('.star').removeClass('hidescn');
				$('.star').css({'animation-name':'animate_star'});
				$('.star').css({'transform':'translate(0,0)'});
			},3000);
			setTimeout(function(){
				$('#11').removeClass('hiddentext');
			},4000);
			setTimeout(function(){
				$('#11').addClass('hiddentext');
				$('#12').removeClass('hiddentext');
			},6000);
			setTimeout(function(){
				$('.grdu').css({'opacity':'1'});
			},7000);
			setTimeout(function(){
				$('.grd').css({'opacity':'0'});
				$('#12').addClass('hiddentext');
				$('#13').removeClass('hiddentext');
			},9000);
			setTimeout(function(){
				$('#13').addClass('hiddentext');
				$('#14').removeClass('hiddentext');
				$('#scrollic').css({'opacity':'1','animation-name':'blink'});
			},11000);
		},25500);
	},5000);
}
